### ISSUE TITLE
IE filter: progid breaks CSSO 1.3.7

### ISSUE THREAD

**Issue by w8r** [css/csso#117]
```css
filter: progid: DXImageTransform.Microsoft.gradient(startColorstr='#b3000000', endColorstr='#e6000000', GradientType=0 );
```
causes

```shell
usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:399
        throw new Error('Please check the validity of the CSS block starting f
              ^
Error: Please check the validity of the CSS block starting from the line #42
    at throwError (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at getBlock (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:755:18)
    at getRuleset (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:1739:22)
    at getStylesheet (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:1936:56)
    at Object.CSSPRules.stylesheet (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:365:69)
    at _getAST (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:409:38)
    at /usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:2287:16
    at Object.srcToCSSP (/usr/local/lib/node_modules/csso/lib/gonzales.cssp.node.js:2292:16)
    at exports.parse (/usr/local/lib/node_modules/csso/lib/cssoapi.js:7:21)
    at Object.exports.justDoIt (/usr/local/lib/node_modules/csso/lib/cssoapi.js:21:41)
```

**Comment by lahmatiy** [comment]
There shouldn't be a space after `progid:`
