### ISSUE TITLE
Installing through npm failed

### ISSUE THREAD

**Issue by TheSisb** [css/csso#123]
I ran npm install csso -g and the csso.js file is missing

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\npm\node_modules\csso\lib\csso.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by lahmatiy** [comment]
Should be fixed by #208
