### ISSUE TITLE
CSSO on Windows error

### ISSUE THREAD

**Issue by Frikki** [css/csso#142]
[C:\]csso

module.js:340
    throw err;
          ^
Error: Cannot find module '\\lib\csso.js\'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by lahmatiy** [comment]
Should be fixed by #208
