### ISSUE TITLE
Error CSS validity

### ISSUE THREAD

**Issue by chrisvidal** [css/csso#206]
Hi

i got this error from gulp csso, but i dont understand the console log to fix the origin of the issue :+1: thks for any help

/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399
        throw new Error('Please check the validity of the CSS block starting f
              ^
Error: Please check the validity of the CSS block starting from the line #1994
    at throwError (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:399:15)
    at checkStylesheet (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:1921:22)
    at Object.CSSPRules.stylesheet (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:365:40)
    at _getAST (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:409:38)
    at exports.srcToCSSP (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2287:16)
    at Object.exports.srcToCSSP (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/gonzales.cssp.node.js:2292:16)
    at exports.parse (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/cssoapi.js:7:21)
    at Object.exports.justDoIt (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/node_modules/csso/lib/cssoapi.js:21:41)
    at Transform.stream._transform (/Users/Tsun/Sites/alpha/node_modules/gulp-csso/index.js:39:34)
    at Transform._read (_stream_transform.js:179:10)

**Comment by lahmatiy** [comment]
@marani Yep, parser don't support for selector list in `:not()`. This was [added in `CSS Selectors Level 4`](https://drafts.csswg.org/selectors-4/#negation) that's still in draft. As I know, only WebKit developers [working](https://webkit.org/blog/3615/css-selectors-inside-selectors-discover-matches-not-and-nth-child/) on it. But I don't know if any released browser support it. If it's an issue, please, fill the separate issue.

@CristianMR  Your example parsing ok.
@sotayamashita Your example parsing ok too.

**Comment by nowherenearithaca** [comment]
While old - just want to saw thanks here.  I was suddenly getting a screwy error with csso and from the notes here alerted me to possible css stuff = in my case, I had an ":ev" instead of ":even" that seemed to be tripping it up
