### ISSUE TITLE
old IE filter properties with DirectX won't work

### ISSUE THREAD

**Issue by DennisBecker** [css/csso#249]
```css
filter: progid: DXImageTransform.Microsoft.gradient(startColorstr='$start', endColorstr='$stop', GradientType=0);
```

CSSO exits with the following error:

```bash
/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:115
    throw new Error('Please check the validity of the CSS block starting from
          ^
Error: Please check the validity of the CSS block starting from the line #11199
    at throwError (/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:115:11)
    at getBlock (/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:523:14)
    at getRuleset (/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:1563:18)
    at getStylesheet (/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:1761:52)
    at Object.CSSPRules.stylesheet (/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:80:65)
    at parse (/Users/becker/github/test-csso/node_modules/csso/lib/parser/index.js:2072:30)
    at Object.minify (/Users/becker/github/test-csso/node_modules/csso/lib/index.js:18:15)
    at /Users/becker/github/test-csso/node_modules/csso/lib/cli.js:38:31
    at ReadStream.<anonymous> (/Users/becker/github/test-csso/node_modules/csso/lib/cli.js:14:13)
    at ReadStream.emit (events.js:129:20)
```

**Comment by lahmatiy** [comment]
One question: you still support for IE7? As this syntax is not valid, even for IE8 (http://blogs.msdn.com/b/ie/archive/2008/09/08/microsoft-css-vendor-extensions.aspx)

Not sure this values should be kept by compressor. Anyway I think csso shouldn't prevent css processing on those values. Going to fix it.

**Comment by DennisBecker** [comment]
I guess we don't support it, autoprefixer should remove them but actually it doesn't. There is some old code with different vendor fixes and newer code using only CSS3. Cleaning the codebase will need some time.

**Comment by lahmatiy** [comment]
I see. Thank you for clarification.
If autoprefixer produce code like this, it's common issue.

**Comment by DennisBecker** [comment]
It can produce such code. I'm sure we have configured it to support IE8 to latest for uses which still use Windows XP.

**Comment by lahmatiy** [comment]
I also see `$start` and `$stop` in value. Looks like a bug too.

**Comment by DennisBecker** [comment]
Seems so, but when you change these to hex colors it also does not work.
