### ISSUE TITLE
Problem with unicode-range parsing (edge case)

### ISSUE THREAD

**Issue by prassh123** [css/csso#250]
With csso version 1.4.0, gulp csso works just fine. However when I upgrade to 1.4.1, it throws this error.

```
Error: Please check the validity of the CSS block starting from the line #2863
  at throwError (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:115:11)
  at getFunctionBody (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1008:13)
  at getFunktion (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:987:9)
  at getAny (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:162:41)
  at _getValue (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1945:36)
  at getValue (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1933:13)
  at getDeclaration (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:767:22)
  at _getBlockdecl0 (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:582:59)
  at getBlockdecl (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:550:24)
  at getBlock (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:522:55)
  at getAtruleb (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:401:30)
  at getAtrule (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:375:24)
  at getStylesheet (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1762:56)
  at Object.CSSPRules.stylesheet (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:80:65)
  at parse (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:2072:30)
  at Object.minify (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/index.js:18:15)
  at Transform.stream._transform (/Users/praghavan/meson/meson/ui/node_modules/gulp-csso/index.js:23:34)
  at Transform._read (_stream_transform.js:179:10)
  at Transform._write (_stream_transform.js:167:12)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at Transform.Writable.write (_stream_writable.js:183:11)
  at write (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform._transform (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/index.js:38:3)
  at DestroyableTransform.Transform._read (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at Stream.ondata (stream.js:51:26)
  at Stream.emit (events.js:95:17)
  at queueData (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:43:21)
  at next (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:71:7)
  at /Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:85:7
  at /Users/praghavan/meson/meson/ui/node_modules/gulp-bytediff/index.js:16:9
  at wrappedMapper (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:84:19)
  at Stream.stream.write (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:96:21)
  at write (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at DestroyableTransform.endStream [as _flush] (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/index.js:98:10)
  at DestroyableTransform.<anonymous> (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:117:20)
  at finishMaybe (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_writable.js:371:12)
  at endWritable (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_writable.js:378:3)
  at DestroyableTransform.Writable.end (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_writable.js:356:5)
  at DestroyableTransform.onend (/Users/praghavan/meson/meson/ui/node_modules/gulp-plumber/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:117:20)
  at /Users/praghavan/meson/meson/ui/node_modules/gulp-plumber/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:442:13)

```

```
node version: v0.10.36
npm version: 3.3.5
gulp-csso version: 1.0.1
```

**Comment by lahmatiy** [comment]
It's regular error when something wrong in CSS (according to the current parser).
Could you provide more details what is around line #2863 in your file.

**Comment by prassh123** [comment]
Well its a minified file and what happens is that i comment the block of code containing the error and then the error shows up in a different place. I reverted and pinned the version to 1.4.0 and its good again. Let me try to provide you additional context.

**Comment by prassh123** [comment]
Here is some more info. The error points to angular-busy css @ https://github.com/cgross/angular-busy/blob/master/dist/angular-busy.css 

```
.cg-busy{
	position:absolute;
	top:0px;
	left:0px;
	right:0px;
	bottom:0px;
    z-index:1001;
}
```
```
File
cwd:      ~/meson/meson/ui
base:     ~/meson/meson/ui/meson-watch/vendor/
path:     ~/meson/meson/ui/meson-watch/vendor/meson-0.0.1.css
contents: .cg-busy{
	position:absolute;
	top:0px;...


/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:103
        throw err
              ^
Error: Please check the validity of the CSS block starting from the line #3181
  at throwError (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:115:11)
  at getFunctionBody (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1008:13)
  at getFunktion (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:987:9)
  at getAny (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:162:41)
  at _getValue (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1945:36)
  at getValue (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1933:13)
  at getDeclaration (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:767:22)
  at _getBlockdecl0 (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:582:59)
  at getBlockdecl (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:550:24)
  at getBlock (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:522:55)
  at getAtruleb (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:401:30)
  at getAtrule (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:375:24)
  at getStylesheet (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:1762:56)
  at Object.CSSPRules.stylesheet (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:80:65)
  at parse (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/parser/index.js:2072:30)
  at Object.minify (/Users/praghavan/meson/meson/ui/node_modules/csso/lib/index.js:18:15)
  at Transform.stream._transform (/Users/praghavan/meson/meson/ui/node_modules/gulp-csso/index.js:23:34)
  at Transform._read (_stream_transform.js:179:10)
  at Transform._write (_stream_transform.js:167:12)
  at doWrite (_stream_writable.js:226:10)
  at writeOrBuffer (_stream_writable.js:216:5)
  at Transform.Writable.write (_stream_writable.js:183:11)
  at write (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform._transform (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/index.js:38:3)
  at DestroyableTransform.Transform._read (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Users/praghavan/meson/meson/ui/node_modules/gulp-debug/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at Stream.ondata (stream.js:51:26)
  at Stream.emit (events.js:95:17)
  at queueData (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:43:21)
  at next (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:71:7)
  at /Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:85:7
  at /Users/praghavan/meson/meson/ui/node_modules/gulp-bytediff/index.js:16:9
  at wrappedMapper (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:84:19)
  at Stream.stream.write (/Users/praghavan/meson/meson/ui/node_modules/map-stream/index.js:96:21)
  at write (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at DestroyableTransform.endStream [as _flush] (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/index.js:98:10)
  at DestroyableTransform.<anonymous> (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:117:20)
  at finishMaybe (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_writable.js:371:12)
  at endWritable (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_writable.js:378:3)
  at DestroyableTransform.Writable.end (/Users/praghavan/meson/meson/ui/node_modules/gulp-concat/node_modules/readable-stream/lib/_stream_writable.js:356:5)
  at DestroyableTransform.onend (/Users/praghavan/meson/meson/ui/node_modules/gulp-plumber/node_modules/readable-stream/lib/_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:117:20)
  at /Users/praghavan/meson/meson/ui/node_modules/gulp-plumber/node_modules/readable-stream/lib/_stream_readable.js:965:16
  at process._tickCallback (node.js:442:13)
```

I dont see anything wrong with that block unless i am missing something thats obvious.

**Comment by julienpa** [comment]
Same issue for me, using gulp-csso in a build script.

> Error: Please check the validity of the CSS block starting from the line # 209

It's funny because CSSO tells me the error is located on block starting at line 209, which is this one:
```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: local('Roboto Light'),
       local('Roboto-Light'),
       url(../assets/fonts/Roboto-Light.woff2) format('woff2'),
       url(../assets/fonts/Roboto-Light.woff) format('woff'),
       url(../assets/fonts/Roboto-Light.ttf) format('truetype');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```

And if I remove the last line, `unicode-range`, then the build works normally.
Why is it funny?
Because right after this block I have 4 others almost exactly the same, and CSSO has no problem with them, example:
```css
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'),
       local('Roboto-Regular'),
       url(../assets/fonts/Roboto-Regular.woff2) format('woff2'),
       url(../assets/fonts/Roboto-Regular.woff) format('woff'),
       url(../assets/fonts/Roboto-Regular.ttf) format('truetype');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2212, U+2215, U+E0FF, U+EFFD, U+F000;
}
```

Any thoughts?

**Comment by lahmatiy** [comment]
@julienpa Thank you! Your comment points to the problem. Already fixed.

@prassh123 @julienpa 
Could you try version from master? If everything is ok – I'm publishing patch version.

**Comment by julienpa** [comment]
@lahmatiy how should I try the master version? CSSO comes in my project as a dependency for `gulp-csso`. Will try as soon as I find out how to do it :smiley:

**Comment by lahmatiy** [comment]
@julienpa 
Well, there are several ways to do so:
- clone `csso` from github and run `node bin/csso your-file.css`
- specify `csso` dependency in `gulp-csso` as `"csso": "css/csso"` instead of current version and re-install dependancies

But I believe it's ok now. Going to publish patch version.

**Comment by julienpa** [comment]
@lahmatiy Will confirm it works for me after testing, even if it's after you published. Thank you very much!

**Comment by lahmatiy** [comment]
@julienpa Already published ;) I hope that the problem is solved

**Comment by julienpa** [comment]
Just tried again without upgrading and... Today it works! :open_mouth: 
Or is it updating the dependency of my project anyway?
```bash
MacBook-Pro-de-Julien:html-client julien$ npm update csso
MacBook-Pro-de-Julien:html-client julien$ 
```
Anyway thanks for the prompt replies @lahmatiy!
