### ISSUE TITLE
TypeError: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by octohedron** [css/csso#260]
```bash
user@WS ~/node/css $ csso -i main-styles-fixed.css -o styles.css

/usr/local/lib/node_modules/csso/bin/csso:15
    throw e;
          ^
TypeError: Cannot call method 'on' of undefined
    at readFromStream (/usr/local/lib/node_modules/csso/lib/cli.js:10:10)
    at Object.action_ (/usr/local/lib/node_modules/csso/lib/cli.js:37:9)
    at Object.Command.run (/usr/local/lib/node_modules/csso/node_modules/clap/index.js:734:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/csso/bin/csso:6:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)

```

**Comment by lahmatiy** [comment]
What version of node.js do you use?

**Comment by lahmatiy** [comment]
As I found it point on call of `on` method of `stream.setEncoding()` result. `setEncoding` become chainable in node.js 0.11.7. So I suppose you use node.js prior 0.12.x. But `csso` doesn't support node.js prior 0.12.x.
Correct me if I wrong.
