### ISSUE TITLE
Can not read property of null

### ISSUE THREAD

**Issue by rkeshmir** [css/csso#273]
/node_modules/csso/lib/compressor/compress/Dimension.js:24
        if (this.declaration.property.name === 'flex') {
                            ^

TypeError: Cannot read property 'property' of null
    at Object.compressDimension (/node_modules/csso/lib/compressor/compress/Dimension.js:24:29)
    at Object.module.exports [as fn] (/node_modules/csso/lib/compressor/compress/index.js:17:29)
    at Object.walkAll (/node_modules/csso/lib/compressor/ast/walk.js:149:10)
    at List.each (/node_modules/csso/lib/utils/list.js:112:12)
    at Object.walkAll (/node_modules/csso/lib/compressor/ast/walk.js:122:27)
    at List.each (//node_modules/csso/lib/utils/list.js:112:12)
    at Object.walkAll /node_modules/csso/lib/compressor/ast/walk.js:122:27)
    at Object.walkAll (/node_modules/csso/lib/compressor/ast/walk.js:65:25)
    at List.each (//node_modules/csso/lib/utils/list.js:112:12)
    at Object.walkAll (/node_modules/csso/lib/compressor/ast/walk.js:58:24)

**Comment by lahmatiy** [comment]
csso 1.6.1 is out with bug fix

**Comment by rkeshmir** [comment]
Thank you
