### ISSUE TITLE
CSS Syntax Error Identifier Deep is expected

### ISSUE THREAD

**Issue by pranay2419** [css/csso#305]
CssSyntaxError: Identifier `deep` is expected
    at parseError (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:77:17)
    at expectIdentifier (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:128:5)
    at getCombinator (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:779:13)
    at getSimpleSelector (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:346:27)
    at getSelector (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:304:31)
    at getRuleset (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:282:9)
    at Object.getStylesheet [as stylesheet] (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:189:33)
    at parse (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/parser/index.js:1611:26)
    at Object.minify (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/csso/lib/index.js:81:9)
    at Transform.stream._transform (/home/zman/Documents/office_git/prod_ganitixweb/ganitix-web/node_modules/gulp-csso/index.js:23:34)

**Comment by lahmatiy** [comment]
Try compress your CSS with CSSO cli or with [web interface](https://css.github.io/csso/csso.html) - it'll show you more details about problem place. Stack trace isn't informative.

**Comment by ujvala-bhumi** [comment]
I also faced same error. When i use gulp build, above error is thrown, without showing line number or any further details. It would have saved time if it has shown line number. 
btw i tried cli and got to know it. Thanks for quick response

**Comment by lahmatiy** [comment]
What version of `gulp-csso` do you use? I just try latest version of `gulp-csso` and got this output:

```
Error: CSS parse error test.css: Identifier `deep` is expected
    1 |just/an/example {}
------------^
```

**Comment by ujvala-bhumi** [comment]
My version is 1.0.1. I ll upgrade it and check

**Comment by lahmatiy** [comment]
Better error output was introduced in gulp-csso `1.1.0`. Current version is `2.0.0`

**Comment by lahmatiy** [comment]
@pranay2419 Does issue still a problem?

**Comment by pranay2419** [comment]
lahmatiy, i compressed individual css files with csso on cli and came to know the syntax error, there was mistake in color name.. 

thanks for the help

**Comment by lahmatiy** [comment]
@pranay2419 Update `gulp-csso` for verbose error output, it would help in future
