### ISSUE TITLE
installation fails node v6.5

### ISSUE THREAD

**Issue by harshes53** [css/csso#315]
Below is the error:

```
~/sandbox/lib/global-npm-repo $ npm install csso --save

> dtrace-provider@0.2.8 install /Users/blahblah/sandbox/lib/global-npm-repo/node_modules/dtrace-provider
> node-gyp rebuild

  ACTION binding_gyp_libusdt_target_build_libusdt .
Building libusdt for x86_64
rm -f *.gch
rm -f *.o
rm -f libusdt.a
rm -f test_usdt
rm -f test_usdt32
rm -f test_usdt64
rm -f test_mem_usage
gcc -O2 -arch x86_64   -c -o usdt.o usdt.c
usdt.c:212:9: warning: implicit declaration of function 'usdt_dof_section_free' is invalid in C99
      [-Wimplicit-function-declaration]
        usdt_dof_section_free(&strtab);
        ^
usdt.c:238:9: warning: implicit declaration of function 'usdt_dof_file_free' is invalid in C99
      [-Wimplicit-function-declaration]
        usdt_dof_file_free(provider->file);
        ^
2 warnings generated.
gcc -O2 -arch x86_64   -c -o usdt_dof_file.o usdt_dof_file.c
gcc -arch x86_64 -o usdt_tracepoints.o -c usdt_tracepoints_x86_64.s
gcc -O2 -arch x86_64   -c -o usdt_probe.o usdt_probe.c
gcc -O2 -arch x86_64   -c -o usdt_dof.o usdt_dof.c
gcc -O2 -arch x86_64   -c -o usdt_dof_sections.o usdt_dof_sections.c
rm -f libusdt.a
ar cru libusdt.a usdt.o usdt_dof_file.o usdt_tracepoints.o usdt_probe.o usdt_dof.o usdt_dof_sections.o
ranlib libusdt.a
  TOUCH Release/obj.target/libusdt.stamp
Release/obj.target/libusdt.stamp { dev: 16777221,
  mode: 33188,
  nlink: 1,
  uid: 501,
  gid: 20,
  rdev: 0,
  blksize: 4096,
  ino: 33420596,
  size: 0,
  blocks: 0,
  atime: 2016-09-08T02:28:25.000Z,
  mtime: 2016-09-08T02:28:25.000Z,
  ctime: 2016-09-08T02:28:25.000Z,
  birthtime: 2016-09-08T02:28:25.000Z }
  CXX(target) Release/obj.target/DTraceProviderBindings/dtrace_provider.o
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:69:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:70:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Fire(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:87:44: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                           ^~~~~~~~~~~~~
                                           v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:88:49: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> AddProbe(const v8::Arguments& args);
                                                ^~~~~~~~~~~~~
                                                v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:89:52: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> RemoveProbe(const v8::Arguments& args);
                                                   ^~~~~~~~~~~~~
                                                   v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:90:47: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Enable(const v8::Arguments& args);
                                              ^~~~~~~~~~~~~
                                              v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:91:48: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Disable(const v8::Arguments& args);
                                               ^~~~~~~~~~~~~
                                               v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
In file included from ../dtrace_provider.cc:1:
../dtrace_provider.h:92:45: error: no type named 'Arguments' in namespace 'v8'; did you mean
      'v8::internal::Arguments'?
    static v8::Handle<v8::Value> Fire(const v8::Arguments& args);
                                            ^~~~~~~~~~~~~
                                            v8::internal::Arguments
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:147:7: note: 'v8::internal::Arguments' declared here
class Arguments;
      ^
../dtrace_provider.cc:23:17: error: calling a protected constructor of class 'v8::HandleScope'
    HandleScope scope;
                ^
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:915:13: note: declared protected here
  V8_INLINE HandleScope() {}
            ^
../dtrace_provider.cc:25:33: error: no matching function for call to 'New'
    Local<FunctionTemplate> t = FunctionTemplate::New(DTraceProvider::New);
                                ^~~~~~~~~~~~~~~~~~~~~
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:4483:34: note: candidate function not viable: no
      known conversion from 'v8::Handle<v8::Value> (const v8::internal::Arguments &)' (aka
      'v8::Local<v8::Value> (const v8::internal::Arguments &)') to 'v8::Isolate *' for 1st argument
  static Local<FunctionTemplate> New(
                                 ^
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:4487:34: note: candidate function not viable:
      requires 6 arguments, but 1 was provided
  static Local<FunctionTemplate> New(
                                 ^
../dtrace_provider.cc:26:58: error: 'New' is a private member of
      'v8::PersistentBase<v8::FunctionTemplate>'
    constructor_template = Persistent<FunctionTemplate>::New(t);
                                                         ^
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:669:23: note: declared private here
  V8_INLINE static T* New(Isolate* isolate, T* that);
                      ^
../dtrace_provider.cc:26:28: error: too few arguments to function call, expected 2, have 1; did you
      mean 'DTraceProbe::New'?
    constructor_template = Persistent<FunctionTemplate>::New(t);
                           ^~~~~~~~~~
                           DTraceProbe::New
../dtrace_provider.h:69:34: note: 'DTraceProbe::New' declared here
    static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                 ^
../dtrace_provider.cc:27:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a
      pointer; did you mean to use '.'?
    constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~~~~~~~~~~~~~~~~~^~
                        .
../dtrace_provider.cc:27:27: error: no member named 'InstanceTemplate' in
      'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    constructor_template->InstanceTemplate()->SetInternalFieldCount(1);
    ~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:25: error: member reference type 'Persistent<v8::FunctionTemplate>' is not a
      pointer; did you mean to use '.'?
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
    ~~~~~~~~~~~~~~~~~~~~^~
                        .
../dtrace_provider.cc:28:27: error: no member named 'SetClassName' in
      'v8::Persistent<v8::FunctionTemplate, v8::NonCopyablePersistentTraits<v8::FunctionTemplate> >'
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
    ~~~~~~~~~~~~~~~~~~~~  ^
../dtrace_provider.cc:28:48: error: no member named 'NewSymbol' in 'v8::String'
    constructor_template->SetClassName(String::NewSymbol("DTraceProvider"));
                                       ~~~~~~~~^
../dtrace_provider.cc:30:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
      'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(constructor_template, "addProbe", DTraceProvider::AddProbe);
                              ^~~~~~~~~~~~~~~~~~~~
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:218:7: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st
      argument
class Local {
      ^
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:218:7: note: candidate constructor
      (the implicit move constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:222:13: note: candidate template ignored: could not
      match 'Local' against 'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/blahblah/.node-gyp/6.5.0/include/node/node.h:273:71: note: passing argument to parameter 'recv'
      here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
../dtrace_provider.cc:31:31: error: no viable conversion from 'Persistent<v8::FunctionTemplate>' to
      'v8::Local<v8::FunctionTemplate>'
    NODE_SET_PROTOTYPE_METHOD(constructor_template, "removeProbe", DTraceProvider::RemoveProbe);
                              ^~~~~~~~~~~~~~~~~~~~
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:218:7: note: candidate constructor
      (the implicit copy constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to 'const v8::Local<v8::FunctionTemplate> &' for 1st
      argument
class Local {
      ^
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:218:7: note: candidate constructor
      (the implicit move constructor) not viable: no known conversion from
      'Persistent<v8::FunctionTemplate>' to 'v8::Local<v8::FunctionTemplate> &&' for 1st argument
/Users/blahblah/.node-gyp/6.5.0/include/node/v8.h:222:13: note: candidate template ignored: could not
      match 'Local' against 'Persistent'
  V8_INLINE Local(Local<S> that)
            ^
/Users/blahblah/.node-gyp/6.5.0/include/node/node.h:273:71: note: passing argument to parameter 'recv'
      here
inline void NODE_SET_PROTOTYPE_METHOD(v8::Local<v8::FunctionTemplate> recv,
                                                                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/DTraceProviderBindings/dtrace_provider.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/blahblah/sandbox/lib/global-npm-repo/node_modules/dtrace-provider
gyp ERR! node -v v6.5.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:dtrace-provider@0.2.8 dtrace-provider@0.2.8 install: `node-gyp rebuild`
npm WARN install:dtrace-provider@0.2.8 Exit status 1
global-npm-repo@0.0.0 /Users/blahblah/sandbox/lib/global-npm-repo
└── csso@2.2.1

npm WARN enoent ENOENT: no such file or directory, open '/Users/blahblah/sandbox/lib/global-npm-repo/node_modules/duplexify/package.json'
npm WARN global-npm-repo@0.0.0 No description
npm WARN global-npm-repo@0.0.0 No repository field.
 ~/sandbox/lib/global-npm-repo $
```

Please help! Thanks!!

**Comment by lahmatiy** [comment]
Seems to me it's problem with your node. So most part of log is about `dtrace-provider` attempt to install and compile. At the end you can see

```
global-npm-repo@0.0.0 /Users/blahblah/sandbox/lib/global-npm-repo
└── csso@2.2.1
```

So `csso` has beed installed successfully.
I tried myself to install `csso` on node.js 6.5. No any problems.

```
~/git/tmp/t19 npm i csso --save
t19@1.0.0 /Users/rdvornov/git/tmp/t19
└─┬ csso@2.2.1
  ├─┬ clap@1.1.1
  │ └─┬ chalk@1.1.3
  │   ├── ansi-styles@2.2.1
  │   ├── escape-string-regexp@1.0.5
  │   ├─┬ has-ansi@2.0.0
  │   │ └── ansi-regex@2.0.0
  │   ├── strip-ansi@3.0.1
  │   └── supports-color@2.0.0
  └── source-map@0.5.6

npm WARN t19@1.0.0 No description
npm WARN t19@1.0.0 No repository field.
~/git/tmp/t19 node -v
v6.5.0
~/git/tmp/t19 npm -v
3.10.3
```
