### ISSUE TITLE
Error: Please check the validity of the CSS block starting from the line #223

### ISSUE THREAD

**Issue by darekarrb** [css/csso#331]
Hi

I got this error from gulp-csso, but i don't understand the console log to fix the origin of the issue.
also try link - https://github.com/css/csso/issues/206

Thanks in advance

C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:404
        throw new Error('Please check the validity of the CSS block starting f
              ^
Error: Please check the validity of the CSS block starting from the line # 223
    at throwError (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:404:15)
    at checkStylesheet (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:1926:22)
    at Object.CSSPRules.stylesheet (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:370:40)
    at _getAST (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:414:38)
    at exports.srcToCSSP (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:2292:16)
    at Object.exports.srcToCSSP (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\gonzales.cssp.node.js:2297:16)
    at exports.parse (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\cssoapi.js:7:21)
    at Object.exports.justDoIt (C:\Proj\MyAppUI\node_modules\gulp-csso\node_modules\csso\lib\cssoapi.js:21:41)
    at Transform.stream._transform (C:\Proj\MyAppUI\node_modules\gulp-csso\index.js:39:34)
    at Transform._read (_stream_transform.js:179:10)

**Comment by lahmatiy** [comment]
You're using too old version of `csso`/`gulp-csso`. `csso` has a verbose error output starting with [1.6.0](https://github.com/css/csso/releases/tag/v1.6.0). The latest version is `3.0.1`. Updating to latest version should help to solve the issue.

**Comment by darekarrb** [comment]
Hi @lahmatiy 
Thanks for the quick help. there is an issue in one of the application css file which causing the issue. that has been rectified and resolved.  
Thanks Again,

- D Rajendra
