### ISSUE TITLE
Better error messages for nested CSS

### ISSUE THREAD

**Issue by ai** [css/csso#370]
I forgot to enable `postcss-nested` plugin and get this error from `CssoWebpackPlugin` on any nested rules `a { b {} }`:

```
Cannot read property '0' of undefined TypeError: Cannot read property '0' of undefined
    at getPropertyDescriptor (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/utils/names.js:65:24)
    at getPropertyFingerprint (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/restructure/6-restructBlock.js:68:20)
    at List.<anonymous> (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/restructure/6-restructBlock.js:213:27)
    at List.eachRight (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/utils/list.js:182:12)
    at Object.processRule (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/restructure/6-restructBlock.js:211:18)
    at Object.enter (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/restructure/6-restructBlock.js:293:25)
    at Object.<anonymous> (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/walker/create.js:13:16)
    at List.walkNode (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/walker/create.js:161:19)
    at List.eachRight (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/utils/list.js:182:12)
    at Object.eval [as StyleSheet] (eval at createTypeIterator (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/walker/create.js:112:12), <anonymous>:5:15)
    at walkNode (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/walker/create.js:158:37)
    at walk (/home/travis/build/evilmartians/amplifr-front/node_modules/css-tree/lib/walker/create.js:214:9)
    at restructBlock (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/restructure/6-restructBlock.js:270:5)
    at module.exports (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/restructure/index.js:27:5)
    at compressChunk (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/compress.js:77:9)
    at compress (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/compress.js:153:9)
    at minify (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/index.js:94:9)
    at Object.minifyStylesheet [as minify] (/home/travis/build/evilmartians/amplifr-front/node_modules/csso/lib/index.js:123:12)
    at /home/travis/build/evilmartians/amplifr-front/node_modules/csso-webpack-plugin/lib/index.js:136:63
    at /home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:3158:5)
    at /home/travis/build/evilmartians/amplifr-front/node_modules/csso-webpack-plugin/lib/index.js:102:37
    at /home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:1055:9)
    at eachOf (/home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/home/travis/build/evilmartians/amplifr-front/node_modules/async/dist/async.js:3158:5)
    at Compilation.<anonymous> (/home/travis/build/evilmartians/amplifr-front/node_modules/csso-webpack-plugin/lib/index.js:101:33)
    at Compilation.applyPluginsAsyncSeries (/home/travis/build/evilmartians/amplifr-front/node_modules/tapable/lib/Tapable.js:206:13)
```

Of course, error should be raised, but I think we should show better error here :).

**Comment by Finesse** [comment]
I request better error messages for every errors. For example, an error for such code (a result of incorrect usage of Stylus):

```css
.foo {
  width: 14px;
  margin-right: -@width;
}
```

Is `undefined is not an object (evaluating 'e.value.children.some')`. I expect either to get no error (CSSO just leaves unknown property values as is) or to get a reference to the bad CSS code in the error message.

**Comment by lahmatiy** [comment]
> I expect either to get no error (CSSO just leaves unknown property values as is) or to get a reference to the bad CSS code in the error message.

@Finesse You're right, no error should occur here.
CSSO can't leave such values as is, because it made many thing complicated when structural optimisation is used. I believe CSSO must omit such declaration. I've fixed similar issues recently, but this case was not addressed.
Can you please to fill a new issue about the case? Since case from initial comment already fixed and not an issue anymore. Thank you in advance!

**Comment by lahmatiy** [comment]
@ai I'm not sure which version it was fixed, but `a { b {} }` not throws any exception now. Looks like it's not an issue anymore.

**Comment by Finesse** [comment]
@lahmatiy Done: https://github.com/css/csso/issues/412
