### ISSUE TITLE
Any selectors from tailwindcss kills csso parser with error "Unexpected input"

### ISSUE THREAD

**Issue by Semdevmaster** [css/csso#428]
Example selector:
.sm\:focus-within\:text-opacity-5:focus-within {}
Get in the console:
SyntaxError: Unexpected input
    at Object.error (.........\node_modules\css-tree\lib\parser\create.js:240:19)
Try this selector in https://hugogiraudel.github.io/selectors-explained/
no error
Is this a parser problem or is it really selector problem?

**Comment by Semdevmaster** [comment]
I tested this selector on pure css and it is fully valid. Apparently the problem is in the parser.

**Comment by lahmatiy** [comment]
Which version of CSSO do you use? Can't reproduce in the latest version:
![image](https://user-images.githubusercontent.com/270491/103762001-df8d9580-5017-11eb-80f3-86eede4846c7.png)

**Comment by Semdevmaster** [comment]
Describe the problem:
Example selector:
.sm\:focus-within\:text-opacity-5:focus-within{}
Get in the console:
SyntaxError: Unexpected input
at Object.error (.........\node_modules\css-tree\lib\parser\create.js:240:19)

Link to a minimal reproduction:
1)default config tailwindcss (use only utilities)
2)add postcss plugin "postcss-csso" in postcss.config.js
3)get above error in console
