### ISSUE TITLE
Пробелы в имени входного файла

### ISSUE THREAD

**Issue by pashinin** [css/csso#74]
Когда я даю входной файл, в имени которого есть пробел, вылетает exception:

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ENOENT, no such file or directory '/var/www/domain/css/css'  <--- после идет пробел
    at Object.openSync (fs.js:230:18)
    at Object.readFileSync (fs.js:120:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/csso/lib/csso.js:30:14)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:32)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:41)

Кавычки -i "/file name.css" не помогают.

Это проблема csso или вообще nodeJS? Что тут делать?

**Comment by lahmatiy** [comment]
Нужно экранировать пробелы: `"file\ name.css"`
